# Generated by Django 2.0.2 on 2020-01-07 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=15, unique=True)),
                ('kode', models.CharField(max_length=4, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('nama_blkg', models.CharField(max_length=50)),
                ('gelar', models.CharField(max_length=10)),
                ('user', models.OneToOneField(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_hari', models.CharField(max_length=10)),
                ('hari', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kelas', models.CharField(max_length=10)),
                ('kelas', models.CharField(max_length=10)),
                ('kapasitas', models.IntegerField()),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mapel', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Penjadwalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_jadwal', models.CharField(max_length=10)),
                ('hari', models.PositiveIntegerField(choices=[(1, 'SENIN'), (2, 'SELASA'), (3, 'RABU'), (4, 'KAMIS'), (5, 'JUMAT'), (6, 'SABTU')], default=1)),
                ('jamke', models.PositiveIntegerField(choices=[(1, '07.00'), (2, '07.40'), (3, '08.20'), (4, '09.00'), (5, '10.00'), (6, '10.20'), (7, '10.40'), (8, '11.20'), (9, '12.30'), (0, 'ISTIRAHAT')], default=1)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.Guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.Kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.Mapel')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=15, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('nama_blkg', models.CharField(max_length=50)),
                ('Kelas', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.Kelas')),
                ('user', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
