# Generated by Django 2.0.2 on 2020-01-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0003_auto_20200107_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='Kelas',
            new_name='kelas',
        ),
    ]
