# Generated by Django 2.0.2 on 2020-01-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0005_pengumuman_surat_ijin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengumuman',
        ),
    ]
