# Generated by Django 2.0.2 on 2020-01-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0008_auto_20200110_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat_ijin',
            name='dokumen',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='doc_suratijin/'),
        ),
    ]
