# Generated by Django 2.0.2 on 2020-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0010_auto_20200110_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='dokumen',
            field=models.ImageField(default='null', upload_to='static/doc_pengumuman/'),
        ),
    ]
