# Generated by Django 2.0.2 on 2020-01-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0013_auto_20200110_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat_ijin',
            name='pengirim',
            field=models.CharField(max_length=200),
        ),
    ]
